spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://${mysql.ipPort}/${mysql.dbName}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8           # 数据库连接地址
    username: ${mysql.username}
    password: ${mysql.password}

app:
  file:
    filename:
      user-json: user.json
      xzqh-excel: 行政区划数据.xlsx
      dict-excel: 字典数据.xlsx
      dict-excel-sheets: 行政区划,姓,名
  remote-service:
    dsc-h-mybatis:
      service-name: dsc-h-mybatis
      # 指定URL访问，不走负载均衡
#      url: http://ip:30006