spring:
  devtools:
    restart:
      additional-paths: src/main/*
app:
  file:
    filename:
      user-json: user.json
      table-excel: 表数据.xlsx
      table-excel-sheets: User,Address
      xzqh-excel: 行政区划数据.xlsx
      baseData-excel: 基础数据.xlsx
      dict-excel: 源字典数据.xlsx
      dict-excel-sheets: xzqh,xing,ming
  remote-service:
    dsc-h-mybatis:
      service-name: dsc-h-mybatis
      # 指定URL访问，不走负载均衡
#      url: http://ip:30006
  pool:
    felEngine:
      maxTotal: 20
      minIdle: 0
      maxIdle: 8