---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/c0Alan/Repo-Config
          searchPaths: respo
          username: your username
          password: your password
      label: master
  application:
    name: config-server

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.80.130:8761/eureka/
