eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/
server:
  port: 8621
spring:
  application:
    name: service-feign
logging:
  config: ./logback-spring.xml