# solr
spring.data.solr.host: http://47.106.106.53:8983/solr/

# 静态资源
spring.mvc.static-path-pattern: /static/**
spring.resources.static-locations: classpath:/static

#前缀，也就是模板存放的路径
spring.thymeleaf.prefix: classpath:/static/
#编码格式
spring.thymeleaf.encoding: UTF-8
#是否开启缓存
spring.thymeleaf.cache: false
#后缀
spring.thymeleaf.suffix: .html
#设置不严格的html
spring.thymeleaf.mode: LEGACYHTML5