eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/
server:
  port: 8612
spring:
  application:
    name: service-ribbon
logging:
  config: classpath:logback-spring.xml
