spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://${mysql.ipPort}/${mysql.dbName}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8           # 数据库连接地址
    username: ${mysql.username}
    password: ${mysql.password}
  devtools:
    restart:
      additional-paths: src/main/*

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.springcloud.entity

xxl:
  job:
    admin:
      addresses: http://${xxl-job.server}/xxl-job-admin
    executor:
      appname: dsc-h-xxljob
      port: 31002
      logpath: /srv/dsc/dsc-h-xxljob/logs/xxl-job-jobhandler
      logretentiondays: 30

app:
  remote-service:
    dsc-h-mybatis:
      service-name: dsc-h-mybatis
      # 指定URL访问，不走负载均衡
#      url: http://ip:30006
    dsc-h-kafka:
      service-name: dsc-h-kafka
    dsc-h-tool:
      service-name: dsc-h-tool