---
#创建用户组
- name: create a group
  group: name={{ group_name }}
  ignore_errors: true

- name: create a user belong to the group
  user: name={{ user_name }} shell=/bin/bash group={{ group_name }} home={{ user_home }}  password={{ user_pwd|password_hash('sha512') }} update_password=always append=yes
  ignore_errors: true

#######################以下步骤在建立ssh免密登录的机器上执行即可############# begin #################### 

#上传 tcp rpm包
- name: scp tcl rpm to target host
  copy: src={{ resources_dir }}/{{ tcl_package_name }} dest=/tmp owner=root group=root
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

#安装tcl软件
- name: install tcl rpm
  yum: name=/tmp/{{ tcl_package_name }} state=present
  become: true
  become_method: su
  become_user: root
  ignore_errors: true
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  
#上传expect软件
- name: scp expect rpm to target host
  copy: src={{ resources_dir }}/{{ expect_package_name }} dest=/tmp owner=root group=root
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  
#安装expect软件
- name: install tcl rpm
  yum: name=/tmp/{{ expect_package_name }} state=present
  become: true
  become_method: su
  become_user: root
  ignore_errors: true
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

#上传至远程主机
- name: scp keyGen.sh to one remote host
  copy: src={{ resources_dir }}/keyGen.sh dest=/tmp mode=0755 owner={{ user_name }} group={{ group_name }}
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

 #上传至远程主机
- name: scp sshIP.sh to one remotehost
  copy: src={{ resources_dir }}/sshIP.sh dest=/tmp mode=0755 owner={{ user_name }} group={{ group_name }}
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

#删除rpm
- name: delete rpm package
  command: rm -rf /tmp/{{ item }}
  with_items:
   - "{{ tcl_package_name }}"
   - "{{ expect_package_name }}"
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

#生成公钥
- name: run keyGen.sh
  command: /tmp/keyGen.sh {{ user_home }}
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  become: yes
  become_method: su
  become_user: "{{ user_name }}"
  ignore_errors: true
  
 
#检测公钥是否创建成功
- name: check whether id_rsa.pub exist
  stat: path={{ user_home }}/.ssh/id_rsa.pub
  register: rsaResult
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

#从远程拉取公钥到本地
- name: get id_rsa.pub from the remote host
  fetch: src={{ user_home }}/.ssh/id_rsa.pub dest=/tmp/ flat=yes
  when: rsaResult.stat.exists
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"

#创建servers.txt
- name: touch servers.txt
  file: dest=/tmp/servers.txt state=touch mode=755 owner={{ user_name }} group={{ group_name }}
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  
#写入ip hostname
- name: write ip hostname into servers.txt
  lineinfile: dest=/tmp/servers.txt line="{{ item }}\r\n{{ hostvars[item]['ansible_hostname'] }}"
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  with_items:
   - "{{ groups['ssh_servers'] }}"

#######################以上步骤在建立ssh免密登录的机器上执行即可############# end ####################

#拷贝公钥
- name: ssh-copy-id  
  authorized_key: user={{ user_name }} state=present key="{{ lookup('file', '/tmp/id_rsa.pub') }}"

- name: ssh ip
  command: /tmp/sshIP.sh
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  become: true
  become_method: su
  become_user: "{{ user_name }}"

- name: rm files
  command: "rm -rf /tmp/{{ item }}"
  run_once: true
  delegate_to: "{{ groups['establish_ip'][0] }}"
  with_items:
    - "servers.txt"
    - "sshIP.sh"
    - "keyGen.sh"
    - "id_rsa.pub"
  become: true
  become_method: su
  become_user: root
