spring:
  profiles:
    active: local
  application:
    name: auto-operation-service
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql//172.25.20.43:3306/videoweb
    username: root
    password: suntek
    driver-class-name: com.mysql.jdbc.Driver

author:
  name: liuxl




