- name: 创建临时目录
  file: path=/opt/tmp state=directory
- name: 安装包拷贝
  copy: src=nginx-1.22.1-1.el7.ngx.x86_64.rpm dest=/opt/tmp/nginx-1.22.1-1.el7.ngx.x86_64.rpm
- name: 安装
  yum: name=/opt/tmp/nginx-1.22.1-1.el7.ngx.x86_64.rpm state=latest
- name: 配置
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  tags: nginxconf
  notify: new conf to reload
- name: 启动
  service: name=nginx state=started enabled=true
- name: 删除临时目录
  file: path=/opt/tmp state=absent