spring:
  devtools:
    restart:
      additional-paths: src/main/*

app:
  remote-service:
    dsc-h-service:
      service-name: dsc-h-service
      # 指定URL访问，不走负载均衡
#      url: http://ip:30006
    dsc-h-web:
      service-name: dsc-h-web
      hello-uri: hello
      feign-uri: feign

