spring:
  devtools:
    restart:
      additional-paths: src/main/*
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
          lower-case-service-id: true






