

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8501/eureka/
server:
  port: 8611
spring:
  application:
    name: service-ribbon

logging:
  cnfig: classpath:logback-spring.xml

