server:
  port: 2101

spring:
  application:
    name: eureka-consumer-ribbon-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

loggin:
  file: logs/${spring.application.name}.log