spring:
  cloud:
    config:
      server:
        native:
#          配置其他应用所需的配置文件的位置位于类路径下的config 目录下
#          配置文件的规则为:应用名十profile.yml.
          search-locations: classpath:/config

server:
  port: 8888
