spring:
  devtools:
    restart:
      additional-paths: src/main/*
  datasource:
    connectionProperties: druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 20
    maxActive: 50
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 30
    password: root
    poolPreparedStatements: true
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${mysql.ipPort}/${mysql.dbName}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: ${mysql.username}
    validationQuery: ${mysql.password}
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    lifecycle:
      timeout-per-shutdown-phase: 10s
    thymeleaf:
      cache: false
      check-template-location: true
      encoding: UTF-8
      mode: HTML5
      prefix: classpath:/templates/
      servlet:
        content-type: text/html
      suffix: .html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

# druid web页面
druid:
  login:
    enabled: false
    password: druid
    username: druid

# 配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  params:
    count: countSql
  reasonable: true
  supportMethodsArguments: true







