server:
  port: 9000


# knife4j
knife4j:
  # 是否开启
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: springboot-2x-web
    description: springboot-2x-web
    concat: liuxl
    version: 1.0.0
    group:
      admin:
        group-name: springboot-2x-web
        api-rule: package
        api-rule-resources:
          - com.demo.springboot
#      front:
#        group-name: 前台接口分组
#        api-rule: package
#        api-rule-resources:
#          - com.itwenke.springbootdemo.knife4j.front

