server:
  port: 8083
spring:
  redis:
    database: 0
    host: 192.168.83.136
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

  #配置数据源
#  datasource:
#    name: test
#    url: jdbc:mysql://192.168.12.57/DB_ATY
#    username: root
#    password: 6789@jkl
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

  #配置数据源 postgresql
#  datasourcePg:
#    name: test
#    url: jdbc:postgresql://192.168.83.136:5432/sd
#    username: postgres
#    password: 12345a

    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.postgresql.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
#    properties:
#       hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect

#  jpa:
#    generate-ddl: false # 是否生成ddl语句
#    show-sql: true # 是否打印sql语句
#    hibernate:
#      ddl-auto: none # 自动生成ddl，由于指定了具体的ddl，此处设置为none
#mybatis:
#  mapper-locations: classpath:mapping/**/*.xml
#  type-aliases-package: com.model.mybatis

#  thymeleaf:
#     cache: false
#     mode: LEGACYHTML5

#pagehelper分页插件
#pagehelper:
#  helperDialect: postgresql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
