---
#用于搭建大数据分析集群，关联spark，es，alluxio,设置es的环境变量
- hosts: es_servers
  gather_facts: true
  remote_user: root
  tasks:
   - name: set es .bash_profile
     lineinfile: dest={{ es_user_home }}/.bash_profile insertafter="{{ item.position }}" line="{{ item.value }}" state=present
     with_items:
      - { position: EOF, value: "\n" }
      - { position: EOF, value: "export ES_PATH={{ install_dir }}/es" }
      - { position: EOF, value: "export SPARK_CORES_MAX={{ spark_cores_max }}" }
      - { position: EOF, value: "export SPARK_EXECUTOR_CORES={{ spark_executor_cores  }}" }
      - { position: EOF, value: "export SPARK_EXECUTOR_MEMORY={{ spark_executor_memory  }} " }
      - { position: EOF, value: "export ALLUXIO_MASTER_URL=alluxio://{{ groups['alluxio_master'][0] }}:19998/dc" }
      - { position: EOF, value: "export SPARK_MASTER_URL=spark://{{ groups['spark_master'][0] }}:7077" }

   - name: source es .bash_profile
     shell: source {{ es_user_home  }}/.bash_profile
