server:
  port: 9090
  servlet:
    context-path: /multiple-datasource

#datasource:
#  aos:
#    jdbc-url: jdbc:mysql://172.25.21.191:3306/auto_operation_system?useUnicode=true&amp;characterEncoding=utf8
#    username: videoweb
#    password: suntek
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
      url: jdbc:mysql://172.25.20.143:3306/ApolloConfigDB?useUnicode=true&amp;characterEncoding=utf8
      username: videoweb
      password: suntek
      driver-class-name: com.mysql.jdbc.Driver


