- name: 创建临时目录
  file: path={{ tmp_dir }} state=directory
- name: 拷贝安装包
  copy: src={{ pkg_name }} dest={{ tmp_dir }}/{{ pkg_name }}
- name: 卸载
  file: path={{ install_dir }} state=absent
- name: 刪除软链
  shell: unlink /usr/local/bin/node ; unlink /usr/local/bin/npm
  ignore_errors: yes
- name: 解压安装
  unarchive: src={{ tmp_dir }}/{{ pkg_name }} dest={{ unarchive_dir }} remote_src=yes
- name: 创建软链
  shell: ln -s {{ install_dir }}/bin/node /usr/local/bin/node ; ln -s {{ install_dir }}/bin/npm /usr/local/bin/npm
  ignore_errors: yes
- name: 清除环境变量
  shell: sed -i '/NODE_HOME/d' {{ env_file }}
- name: 配置环境变量
  lineinfile: dest={{ env_file }} insertafter="{{ item.position }}" line="{{ item.value }}" state=present
  with_items:
    - { position: EOF, value: "\n" }
    - { position: EOF, value: "export NODE_HOME={{ install_dir }}" }
    - { position: EOF, value: "export PATH=$NODE_HOME/bin:$PATH" }
- name: 删除临时目录
  file: path={{ tmp_dir }} state=absent


