spring:
  devtools:
    restart:
      additional-paths: src/main/*
#    add-properties: false
  elasticsearch:
    rest:
      uris: ${elasticsearch7.uris}
      username: ${elasticsearch7.username:}
      password: ${elasticsearch7.password:}

app:
  test:
    users:
      - id: 1
        deptId: 1
        username: aaa
        age: 2
      - id: 2
        deptId: 1
        username: bbb
        age: 2
  remote-service:
    dsc-h-mybatis:
      service-name: dsc-h-mybatis
      # 指定URL访问，不走负载均衡
    #      url: http://ip:30006
    dsc-h-tool:
      file-service: dsc-h-tool/file






