# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 10
    port: 8081
    servlet:
        context-path: /

---
spring:
  profiles: profile1
logging.file: log/baselog.log

---
spring:
  profiles: profile2
logging.file: log/baselog.log
logging.config: classpath:logback-spring.xml


