spring:
  devtools:
    restart:
      additional-paths: src/main/*


# 整合knife4j, 参考: https://blog.csdn.net/ZhangXS9722/article/details/136906546
knife4j:
  enable: true
  openapi:
    title: sch-demo
    description: "sch-demo"
    email: ""
    concat: admin
    url: https://docs.xiaominfo.com
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      sch-demo:
        group-name: sch-demo
        api-rule: package
        api-rule-resources:
          - com.demo.springcloud




